ugent/Studieplekken

authentication-service/blokat-authentication/src/db/db-user/db-user.service.ts, authentication-service/blokat-authentication/src/local-flow/register-flow/register-flow-service.ts
=> fix: Make email case-insensitive

backend/src/main/java/blok2/daos/services/PenaltyService.java
=> chore: Update penalties reset date

authentication-service/blokat-authentication/config/environment/environment.dev.ts, authentication-service/blokat-authentication/src/local-flow/local-flow.controller.ts, authentication-service/blokat-authentication/src/views/login.hbs, authentication-service/blokat-authentication/src/views/register.hbs, backend/src/main/resources/application.yml, frontend/src/environments/environment.ts, frontend/yarn.lock
Providing a bunch of defaults for new developers so you can set up a local environment easier
=> Developer onboarding experience

frontend/src/assets/md/information-penalty.en.md, frontend/src/assets/md/information-penalty.nl.md, frontend/src/assets/md/user-manuals/Handleiding-student.md
=> chore: Remove penalty for refusing to wear a face mask

backend/src/main/java/blok2/controllers/BuildingController.java, backend/src/main/java/blok2/daos/IBuildingDao.java, frontend/src/app/management/building-management/building-management.component.ts
=> Building permissions

frontend/src/app/dashboard/location-details/location-details.component.ts
Fixes a race condition in the location reservation component
=> Reservation fix

backend/src/main/java/blok2/controllers/StatsController.java, backend/src/main/java/blok2/daos/ILocationReservationDao.java, backend/src/main/java/blok2/daos/ITimeslotDao.java, backend/src/main/java/blok2/daos/repositories/LocationReservationRepository.java, backend/src/main/java/blok2/daos/repositories/TimeslotRepository.java, backend/src/main/java/blok2/daos/services/LocationReservationService.java, backend/src/main/java/blok2/daos/services/TimeslotService.java, backend/src/main/java/blok2/model/stats/InstitutionOverviewStat.java, backend/src/main/java/blok2/model/stats/LocationOverviewStat.java, frontend/src/app/management/stats/stats.component.html, frontend/src/app/management/stats/stats.component.ts, frontend/src/app/services/api/endpoints.ts, frontend/src/app/services/api/stats/stats.service.ts, frontend/src/app/shared/model/InstitutionOverviewStat.ts, frontend/src/app/shared/model/LocationOverviewStat.ts, frontend/src/assets/i18n/en.json, frontend/src/assets/i18n/nl.json, frontend/src/styles.scss
=> Add more stats

.github/workflows/test-auth.yml, authentication-service/blokat-authentication/config/environment/environment.test.ts
=> ci: Add auth test workflow

authentication-service/blokat-authentication/src/app.controller.ts, frontend/.npmrc, frontend/package-lock.json, frontend/package.json, frontend/src/app/app.module.ts, frontend/src/app/miscellaneous/barcode/barcode.component.html, frontend/src/app/miscellaneous/barcode/barcode.component.scss, frontend/src/app/miscellaneous/barcode/barcode.component.spec.ts, frontend/src/app/miscellaneous/barcode/barcode.component.ts, frontend/src/app/profile/profile-overview/profile-overview.component.html
=> Add barcode to profile so scanners can use the scan devices

frontend/package-lock.json, frontend/package.json, frontend/src/app/app.component.html, frontend/src/app/dashboard/location-details/location-details.component.html, frontend/src/app/login/login.component.html, frontend/src/app/management/action-log/action-log.component.html, frontend/src/app/management/admins-management/admins-management.component.html, frontend/src/app/management/authorities-management/authorities-management.component.html, frontend/src/app/management/authorities-management/authority-users-management/authority-users-management.component.html, frontend/src/app/management/building-management/building-management.component.html, frontend/src/app/management/locations-management/locations-management.component.html, frontend/src/app/management/locations-management/locations-management.component.scss, frontend/src/app/management/management.component.html, frontend/src/app/management/management.component.ts, frontend/src/app/management/stats/chart/chart.component.html, frontend/src/app/management/tags-management/tags-management.component.html, frontend/src/app/profile/profile-overview/profile-overview.component.html, frontend/src/app/shared/penalties/penalty-table/penalty-table.component.html, frontend/src/assets/styles/production/styles.scss
This PR introduces Bootstrap 5 support in the application (and some layout fixes).
=> Add Bootstrap support

backend/src/main/java/blok2/controllers/TimeslotController.java, frontend/src/app/management/locations-management/location-details-management/location-calendar/location-add-timeslot-dialog/location-add-timeslot-dialog.component.html, frontend/src/app/management/locations-management/location-details-management/location-calendar/location-add-timeslot-dialog/location-add-timeslot-dialog.component.ts, frontend/src/app/management/locations-management/location-details-management/location-calendar/location-calendar.component.html, frontend/src/app/management/locations-management/location-details-management/location-calendar/location-calendar.component.ts, frontend/src/app/services/api/calendar-periods/timeslot.service.ts, frontend/src/app/services/api/endpoints.ts, frontend/src/app/shared/model/Timeslot.ts, frontend/src/assets/i18n/en.json, frontend/src/assets/i18n/nl.json
=> Allow to update an existing timeslot and allow to specify custom amount of seats on creation for a timeslot

backend/README.md, backend/src/main/java/blok2/daos/services/LocationService.java, backend/src/main/java/blok2/stadgent/controllers/StadGentLocationController.java, backend/src/main/java/blok2/stadgent/model/StadGentLocation.java
The Stad Gent API endpoint now returns the active locations sorted by relevance (based on availability and occupancy).
=> Location relevance order

frontend/src/app/components/login/login.component.html, frontend/src/app/components/login/login.component.scss, frontend/src/app/components/management/authorities-management/authority-users-management/authority-users-management.component.ts, frontend/src/app/components/management/locations-management/location-details-management/location-calendar/location-calendar.component.html, frontend/src/app/components/management/stats/stats.component.html, frontend/src/assets/i18n/nl.json
Fixed the statistics page layout where single location statistics were not displayed correctly in their parent row. Also added further login page clarifications to eliminate all doubt when trying to log in as a student or administrator.
=> Stats layout fix

frontend/src/app/components/dashboard/location-reservation/location-reservation.component.html, frontend/src/app/components/dashboard/location-reservation/location-reservation.component.ts, frontend/src/app/extensions/model/LocationReservation.ts, frontend/src/assets/styles/production/components/calendar.scss
The search form dissapeared due to earlier refactoring and was restored.
=> Fixed the modal for adding volunteers to a location

frontend/src/app/components/dashboard/location-reservation/location-reservation.component.html, frontend/src/app/components/dashboard/location-reservation/location-reservation.component.ts, frontend/src/app/extensions/model/LocationReservation.ts, frontend/src/assets/styles/production/components/calendar.scss
Some extra location reservation component improvements.
=> chore: extra color feedback + filtered table on non deleted reservations

frontend/src/app/app.component.ts, frontend/src/app/app.constants.ts, frontend/src/app/app.module.ts, frontend/src/app/components/dashboard/location-reservation/location-reservation.component.html, frontend/src/app/components/dashboard/location-reservation/location-reservation.component.ts, frontend/src/app/components/dashboard/location-reservation/map/map.component.ts, frontend/src/app/components/information/information.component.ts, frontend/src/app/components/management/building-management/building-management.component.ts, frontend/src/app/components/management/locations-management/location-details-management/details-form/details-form.component.ts, frontend/src/app/components/management/locations-management/location-details-management/location-details-management.component.ts, frontend/src/app/components/management/locations-management/locations-management.component.ts, frontend/src/app/components/management/management.component.ts, frontend/src/app/components/management/users-management/user-details-management/user-details-form/user-details-form.component.ts, frontend/src/app/components/navigation/navigation.component.ts, frontend/src/app/components/profile/profile-reservations/profile-reservations.component.ts, frontend/src/app/extensions/model/LocationReservation.ts, frontend/src/app/extensions/model/User.ts, frontend/src/app/extensions/services/api/penalties/penalty.service.ts, frontend/src/app/extensions/services/authentication/authentication.service.ts, frontend/src/app/extensions/services/guard/authorization/authorization-guard.service.ts, frontend/src/app/stad-gent-components/header/breadcrumbs/breadcrumb.service.ts, frontend/src/app/stad-gent-components/header/dropdown/dropdown.component.html, frontend/src/app/stad-gent-components/header/dropdown/dropdown.component.ts, frontend/src/app/stad-gent-components/header/header.component.html, frontend/src/app/stad-gent-components/header/header.component.scss, frontend/src/app/stad-gent-components/header/header.component.ts
Methods like isLoggedIn(), isAdmin() etc... should not reside in the authentication service as it can sometimes be ambiguous when the user has been fetched. In order to prevent race conditions, these methods were moved in the user class. The application loads an empty user on page load, before replacing it with the user from the backend. Now we don't need to worry about undefined users anymore.
=> Authentication service improvements

backend/src/main/java/blok2/database/services/PenaltyService.java
Updated the penalty reset date to August 1. 2023
=> chore: update penalty reset date to august 2023

frontend/src/app/components/dashboard/location-reservation/location-reservation.component.ts, frontend/src/assets/images/Spinner-1s-197px (2).gif:Zone.Identifier
Increased the automatic refresh interval to 1 minute to prevent flood of requests during peak usage
=> chore: increased the location refresh interval

frontend/src/app/components/dashboard/location-reservation/location-reservation-calendar/location-reservation-calendar.component.html, frontend/src/app/components/dashboard/location-reservation/location-reservation-calendar/location-reservation-calendar.component.ts, frontend/src/app/components/dashboard/location-reservation/location-reservation.component.html, frontend/src/app/components/dashboard/location-reservation/location-reservation.component.ts
=> Location reservation popup fix

frontend/src/app/components/dashboard/location-reservation/location-reservation.component.ts
Made a not so very smart error when calculating the reservability of a timeslot based on the reservable timeslot date...
=> fix: popup for reservable timeslots

frontend/src/app/components/dashboard/location-reservation/location-reservation.component.ts, frontend/src/app/components/management/lists/building-management/building-management.component.ts, frontend/src/app/components/management/lists/locations-management/locations-management.component.ts, frontend/src/app/extensions/cache/Cache.ts, frontend/src/app/extensions/services/addressresolver/nomenatim/addressresolver.service.ts
For some reason, geocode.maps.co returned a CORS error message. Switched back to Nomenatim and everything looks good again.
=> fix: address resolver

backend/src/main/java/blok2/database/services/PenaltyService.java
- Updated penalty points reset date for the spring break
=> chore: updated penalty reset date

frontend/src/app/components/dashboard/location-reservation/location-reservation-calendar/location-reservation-calendar.component.html, frontend/src/app/components/management/lists/locations-management/location-details-management/location-calendar/location-add-timeslot-dialog/location-add-timeslot-dialog.component.html, frontend/src/app/components/management/lists/locations-management/location-details-management/location-calendar/location-add-timeslot-dialog/location-add-timeslot-dialog.component.ts, frontend/src/app/components/management/lists/locations-management/location-details-management/location-calendar/location-calendar.component.ts, frontend/src/app/components/management/lists/locations-management/location-details-management/location-details-management.component.ts, frontend/src/app/extensions/services/timeslots/timeslot-calendar-event/timeslot-calendar-event.service.ts
=> fix: null pointer while updating a timeslot's reservable from date

backend/.jpb/jpb-settings.xml, frontend/src/app/app.component.html, frontend/src/app/app.component.ts, frontend/src/assets/i18n/en.json, frontend/src/assets/i18n/nl.json
- Added global status messages with dismiss functionality
=> feat: status messages

frontend/src/app/app.component.html, frontend/src/assets/i18n/en.json, frontend/src/assets/i18n/nl.json
Removed the note stating the Thermi was unavailable due to maintenance
=> chore: removed thermi note

frontend/src/app/app.constants.ts, frontend/src/app/components/dashboard/location-reservation/location-reservation-calendar/location-reservation-calendar.component.html, frontend/src/app/components/dashboard/location-reservation/location-reservation-calendar/location-reservation-calendar.component.ts, frontend/src/app/components/dashboard/location-reservation/location-reservation-details/location-reservation-details.component.html, frontend/src/app/components/dashboard/location-reservation/location-reservation-details/location-reservation-details.component.ts, frontend/src/app/components/dashboard/location-reservation/location-reservation.component.html, frontend/src/app/components/dashboard/location-reservation/location-reservation.component.ts, frontend/src/app/components/management/faq-management/faq-management.component.html, frontend/src/app/model/User.ts, frontend/src/app/pipes/FormatStatusPipe.ts, frontend/src/app/services/authentication/login-redirect.service.ts, frontend/src/app/services/timeslots/timeslot-calendar-event/timeslot-calendar-event.service.ts, frontend/src/assets/i18n/en.json, frontend/src/assets/i18n/nl.json, frontend/tsconfig.app.json
- Fixed an issue where reserved timeslots didn't appear to be selected on the calendar
- Added automatic redirection to last visited location upon login
- Cleaned up the timeslot to event service and other ugly code
=> Reservation improvements

deploy-staging.sh, deploy.sh, frontend/src/app/components/management/locations-management/location-details-management/location-calendar/location-calendar.component.html, frontend/src/app/components/scan/scanning-location-details/scanning-location-details.component.html, frontend/src/app/components/scan/scanning-location-details/scanning-location-details.component.ts, frontend/src/app/components/shared/inputs/moment-date/moment-date.component.html, frontend/src/app/components/shared/inputs/moment-date/moment-date.component.ts, frontend/src/app/components/shared/scanner/scanner.component.ts, frontend/src/assets/i18n/en.json, frontend/src/assets/i18n/nl.json
- Fixed the `moment-date` component so it properly handles date times
- Disabled automatic torch on mobile devices when scanning, as it introduces an annoying glare in many cases
- Added the option to automatically confirm reservations upon scanning them with the mobile scan
=> Timeslot update fix and scanner improvements
